[database]
host = 127.0.0.1
port = 5432
database = telegram_postgres
user = xah7p
password = xah7p
version_table = public.schema_version

[data]
# Any fields in the data section are available in migration templates
# prefix = foo
